# Generated by Django 3.2.18 on 2023-04-07 22:39

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('gender', models.TextField(choices=[('Не выбрано', 'Не выбрано'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default=('Не выбрано', 'Не выбрано'), verbose_name='Пол')),
                ('username_style', models.TextField(choices=[('gray-un', '.gray-un'), ('white-shadow-un', '.white-shadow-un'), ('grad-wb-un', '.grad-wb-un'), ('red-shadow-un', '.red-shadow-un'), ('grad-pwv-un', '.grad-pwv-un'), ('grad-bvr-un', '.grad-bvr-un'), ('grad-p-double-un', '.grad-p-double-un'), ('pink-shadow-un', '.pink-shadow-un'), ('purple-shadow-un', '.purple-shadow-un'), ('light-green-shadow-un', '.light-green-shadow-un'), ('grad-wp-un', '.grad-wp-un'), ('grad-wy-un', '.grad-wy-un'), ('grad-pp-un', '.grad-pp-un'), ('light-red-shadow-un', '.light-red-shadow-un'), ('blue-shadow-un', '.blue-shadow-un'), ('white-double-shadow-un', '.white-double-shadow-un'), ('blue-light-shadow-un', '.blue-light-shadow-un'), ('dark-green-shadow-un', '.dark-green-shadow-un'), ('blue-p-shadow-un', '.blue-p-shadow-un'), ('black-shadow-un', '.black-shadow-un'), ('red-orange-shadow-un', '.red-orange-shadow-un'), ('light-blue-double-shadow-un', '.light-blue-double-shadow-un'), ('aquamarine-shadow-un', '.aquamarine-shadow-un')], default=('gray-un', '.gray-un'), verbose_name='Стиль имени')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('occupation', models.CharField(default='', max_length=200, verbose_name='Род занятий')),
                ('interests', models.CharField(default='', max_length=200, verbose_name='Интересы')),
                ('description', models.CharField(default='', max_length=200, verbose_name='Описание')),
                ('rank', models.TextField(default='пользователь', verbose_name='Ранг')),
                ('messages', models.IntegerField(default=0, verbose_name='Сообщения')),
                ('tg_link', models.CharField(blank=True, default='', max_length=70, verbose_name='Ссылка на телеграм')),
                ('subscriber', models.IntegerField(default=0, verbose_name='Подписчики')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
