# Generated by Django 3.2.16 on 2023-01-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='', verbose_name='Аватарка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.IntegerField(default=1, verbose_name='Лайки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='subsciber',
            field=models.IntegerField(default=2, verbose_name='Подписчики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_link',
            field=models.TextField(default=3, verbose_name='Ссылка на телеграм'),
            preserve_default=False,
        ),
    ]
