# Generated by Django 3.2.18 on 2023-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner',
            field=models.TextField(choices=[('gray-role', '.gray-role'), ('green-yellow-role', '.green-yellow-role'), ('milk-pink-role', '.milk-pink-role'), ('purple-aquamarine-role', '.purple-aquamarine-role'), ('red-purple-role', '.red-purple-role'), ('yellow-green-role', '.yellow-green-role'), ('blue-pink-role', '.blue-pink-role')], default='gray-role', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_link',
            field=models.SlugField(blank=True, default='', max_length=70, verbose_name='Ссылка на телеграм'),
        ),
    ]
