# Generated by Django 3.2.18 on 2023-05-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='buy_privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('продавец', 'продавец'), ('доверенный продавец', 'доверенный продавец'), ('партнёр', 'партнёр')], default='нет привилегий', verbose_name='Привилегия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('куратор', 'куратор'), ('арбитр', 'арбитр'), ('администратор', 'администратор'), ('бот', 'бот'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default='куратор', verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('куратор', 'куратор'), ('арбитр', 'арбитр'), ('администратор', 'администратор'), ('бот', 'бот'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default='куратор', verbose_name='Ранг'),
        ),
    ]
