# Generated by Django 3.2.16 on 2023-01-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230122_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subsciber',
            field=models.IntegerField(default=0, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_link',
            field=models.TextField(default='https://t.me/sp1edh4ck', verbose_name='Ссылка на телеграм'),
        ),
    ]
