# Generated by Django 3.2.18 on 2023-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('владелец', 'владелец'), ('гл. администратор', 'гл. администратор'), ('администратор', 'администратор'), ('арбитр', 'арбитр'), ('куратор', 'куратор'), ('пользователь', 'пользователь')], default=('пользователь', 'пользователь'), verbose_name='Ранг'),
        ),
    ]
