# Generated by Django 3.2.18 on 2023-04-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230414_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='Уник'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('продавец', 'продавец'), ('доверенный продавец', 'доверенный продавец'), ('партнёр', 'партнёр'), ('наставник', 'наставник'), ('исскуственный интелект', 'исскуственный интелект')], default='нет привилегий', verbose_name='Привилегия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_link',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Ссылка на телеграм'),
        ),
    ]
