# Generated by Django 3.2.18 on 2023-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230513_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('пользователь', 'пользователь'), ('заблокирован', 'заблокирован'), ('местный', 'местный'), ('постоялец', 'постоялец'), ('эксперт', 'эксперт'), ('гуру', 'гуру'), ('исскуственный интелект', 'исскуственный интелект')], default='пользователь', verbose_name='Ранг'),
        ),
    ]
