# Generated by Django 3.2.18 on 2023-12-05 21:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231202_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 21, 54, 17, 455284, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 21, 54, 17, 455284, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 12, 5, 21, 54, 17, 455284, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_style',
            field=models.TextField(choices=[('gray-un', '.gray-un'), ('white-shadow-un', '.white-shadow-un'), ('melt-white', '.melt-white'), ('purple-white-un', '.purple-white-un'), ('grad-wb-un', '.grad-wb-un'), ('red-shadow-un', '.red-shadow-un'), ('grad-pwv-un', '.grad-pwv-un'), ('grad-bvr-un', '.grad-bvr-un'), ('grad-p-double-un', '.grad-p-double-un'), ('pink-shadow-un', '.pink-shadow-un'), ('purple-shadow-un', '.purple-shadow-un'), ('light-green-shadow-un', '.light-green-shadow-un'), ('grad-wp-un', '.grad-wp-un'), ('grad-wy-un', '.grad-wy-un'), ('grad-pp-un', '.grad-pp-un'), ('light-red-shadow-un', '.light-red-shadow-un'), ('blue-shadow-un', '.blue-shadow-un'), ('white-double-shadow-un', '.white-double-shadow-un'), ('blue-light-shadow-un', '.blue-light-shadow-un'), ('dark-green-shadow-un', '.dark-green-shadow-un'), ('blue-p-shadow-un', '.blue-p-shadow-un'), ('black-shadow-un', '.black-shadow-un'), ('red-orange-shadow-un', '.red-orange-shadow-un'), ('light-blue-double-shadow-un', '.light-blue-double-shadow-un'), ('aquamarine-shadow-un', '.aquamarine-shadow-un'), ('green-so-beautifull-un', '.green-so-beautifull-un')], default='gray-un', verbose_name='Стиль имени'),
        ),
    ]
