# Generated by Django 3.2.18 on 2023-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('нет ранга', 'нет ранга'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('администратор', 'администратор'), ('бот', 'бот'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default='нет ранга', verbose_name='Ранг'),
        ),
    ]
