# Generated by Django 3.2.18 on 2023-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('продавец', 'продавец'), ('доверенный продавец', 'доверенный продавец'), ('партнёр', 'партнёр'), ('наставник', 'наставник'), ('исскуственный интелект', 'исскуственный интелект')], default=('нет привилегий', 'нет привилегий'), verbose_name='Привилегия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('владелец', 'владелец'), ('гл. администратор', 'гл. администратор'), ('администратор', 'администратор'), ('бот', 'бот'), ('арбитр', 'арбитр'), ('куратор', 'куратор'), ('пользователь', 'пользователь')], default=('куратор', 'куратор'), verbose_name='Ранг'),
        ),
    ]
