# Generated by Django 3.2.16 on 2023-01-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230122_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.TextField(default='пользователь', verbose_name='Ранг'),
        ),
    ]
