# Generated by Django 3.2.18 on 2023-04-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230405_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.TextField(default='', verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.TextField(default='', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.TextField(default='', verbose_name='Род занятий'),
        ),
    ]
