# Generated by Django 3.2.18 on 2023-06-07 19:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230528_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 19, 43, 24, 306836, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 19, 43, 24, 306836, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 19, 43, 24, 306836, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
        migrations.CreateModel(
            name='IpUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=19, verbose_name='Ip-адресс пользователя')),
                ('banned', models.BooleanField(default=False, verbose_name='Блокировка ip-адресса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
