# Generated by Django 3.2.18 on 2023-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230414_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Симпатии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('пользователь', 'пользователь'), ('заблокирован', 'заблокирован'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('администратор', 'администратор'), ('бот', 'бот'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default='пользователь', verbose_name='Ранг'),
        ),
    ]
