# Generated by Django 3.2.16 on 2023-01-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subsciber',
            new_name='subscriber',
        ),
    ]
