# Generated by Django 3.2.18 on 2023-06-07 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230607_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IpUsers',
            new_name='IpUser',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 20, 11, 11, 463848, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 20, 11, 11, 463848, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 6, 7, 20, 11, 11, 463848, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
    ]
