# Generated by Django 3.2.18 on 2023-04-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230405_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.TextField(default='', verbose_name='Интересы'),
        ),
    ]
