# Generated by Django 3.2.18 on 2023-05-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('нет ранга', 'нет ранга'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('бот', 'бот'), ('администратор', 'администратор'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default='нет ранга', verbose_name='Ранг'),
        ),
    ]
