# Generated by Django 3.2.16 on 2023-01-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_subsciber_customuser_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='messages',
            field=models.IntegerField(default=0, verbose_name='Сообщения'),
        ),
    ]
