# Generated by Django 3.2.18 on 2023-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('нет ранга', 'нет ранга'), ('местный', 'местный'), ('постоялец', 'постоялец'), ('эксперт', 'эксперт'), ('гуру', 'гуру'), ('исскуственный интелект', 'исскуственный интелект')], default='нет ранга', verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('пользователь', 'пользователь'), ('заблокирован', 'заблокирован'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('бот', 'бот'), ('администратор', 'администратор'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default='пользователь', verbose_name='Ранг'),
        ),
    ]
