# Generated by Django 3.2.18 on 2023-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
