# Generated by Django 3.2.18 on 2023-11-17 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230607_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.AddField(
            model_name='customuser',
            name='brt_day',
            field=models.DateField(blank=True, null=True, verbose_name='День'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='brt_month',
            field=models.DateField(blank=True, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='brt_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 18, 8, 7, 943530, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 18, 8, 7, 943530, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 18, 8, 7, 943530, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
    ]
