# Generated by Django 3.2.18 on 2023-04-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_profile_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фон профиля'),
        ),
    ]
