# Generated by Django 3.2.16 on 2023-02-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.TextField(default='EN', verbose_name='Язык'),
        ),
    ]
