# Generated by Django 3.2.18 on 2023-04-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('пользователь', 'пользователь'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('администратор', 'администратор'), ('бот', 'бот'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default=('пользователь', 'пользователь'), verbose_name='Ранг'),
        ),
    ]
