# Generated by Django 3.2.18 on 2023-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230514_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='market_privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('продавец', 'продавец'), ('доверенный продавец', 'доверенный продавец'), ('партнёр', 'партнёр')], default='нет привилегий', verbose_name='Привилегия на маркете'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='buy_privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('легенда', 'легенда'), ('суприм', 'суприм'), ('уник', 'уник')], default='нет привилегий', verbose_name='Платные привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('местный', 'местный'), ('постоялец', 'постоялец'), ('эксперт', 'эксперт'), ('гуру', 'гуру'), ('исскуственный интелект', 'исскуственный интелект')], default='нет привилегий', verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('пользователь', 'пользователь'), ('заблокирован', 'заблокирован'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('бот', 'бот'), ('администратор', 'администратор'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default='пользователь', verbose_name='Должность'),
        ),
    ]
