# Generated by Django 3.2.18 on 2023-05-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230514_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='legend',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='supreme',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='unique',
        ),
    ]
