# Generated by Django 3.2.16 on 2023-02-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.TextField(default='ru', verbose_name='Язык'),
        ),
    ]
