# Generated by Django 3.2.18 on 2023-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legend',
            field=models.BooleanField(default=False, verbose_name='Легенда'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='supreme',
            field=models.BooleanField(default=False, verbose_name='Суприм'),
        ),
    ]
