# Generated by Django 3.2.18 on 2023-11-17 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20231117_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='brt_day',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='brt_month',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='brt_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 18, 14, 7, 962219, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 18, 14, 7, 962219, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 11, 17, 18, 14, 7, 962219, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
    ]
