# Generated by Django 3.2.18 on 2023-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banner',
            field=models.TextField(choices=[('green-yellow-role', '.green-yellow-role'), ('milk-pink-role', '.milk-pink-role'), ('purple-aquamarine-role', '.purple-aquamarine-role'), ('red-purple-role', '.red-purple-role'), ('yellow-green-role', '.yellow-green-role'), ('blue-pink-role', '.blue-pink-role')], default=('green-yellow-role', '.green-yellow-role'), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('пользователь', 'пользователь'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('администратор', 'администратор'), ('бот', 'бот'), ('гл. администр атор', 'гл. администратор'), ('владелец', 'владелец')], default=('пользователь', 'пользователь'), verbose_name='Ранг'),
        ),
    ]
