# Generated by Django 3.2.18 on 2023-11-19 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20231117_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank_lvl',
            field=models.TextField(choices=[(1, 1), (0, 0), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 11, 19, 19, 6, 42, 711143, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 11, 19, 19, 6, 42, 711143, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 11, 19, 19, 6, 42, 711143, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
    ]
