# Generated by Django 3.2.18 on 2023-05-14 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230514_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата покупки привилегии'),
            preserve_default=False,
        ),
    ]
