# Generated by Django 3.2.18 on 2023-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner',
            field=models.TextField(choices=[('green-yellow-role', '.green-yellow-role'), ('milk-pink-role', '.milk-pink-role'), ('purple-aquamarine-role', '.purple-aquamarine-role'), ('red-purple-role', '.red-purple-role'), ('yellow-green-role', '.yellow-green-role'), ('blue-pink-role', '.blue-pink-role')], default='green-yellow-role', verbose_name=''),
        ),
    ]
