# Generated by Django 3.2.18 on 2023-05-14 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230514_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 14, 54, 4, 692484, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 14, 54, 4, 692484, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 14, 54, 4, 692484, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
    ]
