# Generated by Django 3.2.18 on 2023-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.TextField(choices=[('Не выбрано', 'Не выбрано'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Не выбрано', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('продавец', 'продавец'), ('доверенный продавец', 'доверенный продавец'), ('партнёр', 'партнёр'), ('наставник', 'наставник'), ('исскуственный интелект', 'исскуственный интелект')], default='нет привилегий', verbose_name='Привилегия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('пользователь', 'пользователь'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('администратор', 'администратор'), ('бот', 'бот'), ('гл. администр атор', 'гл. администратор'), ('владелец', 'владелец')], default='пользователь', verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_style',
            field=models.TextField(choices=[('gray-un', '.gray-un'), ('white-shadow-un', '.white-shadow-un'), ('grad-wb-un', '.grad-wb-un'), ('red-shadow-un', '.red-shadow-un'), ('grad-pwv-un', '.grad-pwv-un'), ('grad-bvr-un', '.grad-bvr-un'), ('grad-p-double-un', '.grad-p-double-un'), ('pink-shadow-un', '.pink-shadow-un'), ('purple-shadow-un', '.purple-shadow-un'), ('light-green-shadow-un', '.light-green-shadow-un'), ('grad-wp-un', '.grad-wp-un'), ('grad-wy-un', '.grad-wy-un'), ('grad-pp-un', '.grad-pp-un'), ('light-red-shadow-un', '.light-red-shadow-un'), ('blue-shadow-un', '.blue-shadow-un'), ('white-double-shadow-un', '.white-double-shadow-un'), ('blue-light-shadow-un', '.blue-light-shadow-un'), ('dark-green-shadow-un', '.dark-green-shadow-un'), ('blue-p-shadow-un', '.blue-p-shadow-un'), ('black-shadow-un', '.black-shadow-un'), ('red-orange-shadow-un', '.red-orange-shadow-un'), ('light-blue-double-shadow-un', '.light-blue-double-shadow-un'), ('aquamarine-shadow-un', '.aquamarine-shadow-un')], default='gray-un', verbose_name='Стиль имени'),
        ),
    ]
