# Generated by Django 3.2.18 on 2023-05-14 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230514_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('местный', 'местный'), ('постоялец', 'постоялец'), ('эксперт', 'эксперт'), ('гуру', 'гуру'), ('искусственный интелект', 'искусственный интелект')], default='нет привилегий', verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 21, 8, 4, 996712, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 21, 8, 4, 996712, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 21, 8, 4, 996712, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
    ]
