# Generated by Django 3.2.18 on 2023-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230410_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='banner',
            field=models.TextField(choices=[('green-yellow-role', '.green-yellow-role'), ('milk-pink-role', '.milk-pink-role'), ('purple-aquamarine-role', '.purple-aquamarine-role'), ('red-purple-role', '.red-purple-role'), ('yellow-green-role', '.yellow-green-role'), ('blue-pink-role', '.blue-pink-role')], default='green-yellow-role', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username_style',
            field=models.TextField(choices=[('gray-un', '.gray-un'), ('white-shadow-un', '.white-shadow-un'), ('grad-wb-un', '.grad-wb-un'), ('red-shadow-un', '.red-shadow-un'), ('grad-pwv-un', '.grad-pwv-un'), ('grad-bvr-un', '.grad-bvr-un'), ('grad-p-double-un', '.grad-p-double-un'), ('pink-shadow-un', '.pink-shadow-un'), ('purple-shadow-un', '.purple-shadow-un'), ('light-green-shadow-un', '.light-green-shadow-un'), ('grad-wp-un', '.grad-wp-un'), ('grad-wy-un', '.grad-wy-un'), ('grad-pp-un', '.grad-pp-un'), ('light-red-shadow-un', '.light-red-shadow-un'), ('blue-shadow-un', '.blue-shadow-un'), ('white-double-shadow-un', '.white-double-shadow-un'), ('blue-light-shadow-un', '.blue-light-shadow-un'), ('dark-green-shadow-un', '.dark-green-shadow-un'), ('blue-p-shadow-un', '.blue-p-shadow-un'), ('black-shadow-un', '.black-shadow-un'), ('red-orange-shadow-un', '.red-orange-shadow-un'), ('light-blue-double-shadow-un', '.light-blue-double-shadow-un'), ('aquamarine-shadow-un', '.aquamarine-shadow-un')], default='gray-un', verbose_name='Стиль имени'),
        ),
    ]
