# Generated by Django 3.2.18 on 2023-05-14 23:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230515_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='save_deposit',
            field=models.IntegerField(default=0, verbose_name='Страховой депозит'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 23, 14, 45, 858675, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 23, 14, 45, 858675, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 23, 14, 45, 858675, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
    ]
