# Generated by Django 3.2.18 on 2023-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230410_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='privilege',
            field=models.TextField(choices=[('нет привилегий', 'нет привилегий'), ('продавец', 'продавец'), ('доверенный продавец', 'доверенный продавец'), ('партнёр', 'партнёр'), ('наставник', 'наставник'), ('исскуственный интелект', 'исскуственный интелект'), ('уник', 'уник')], default='нет привилегий', verbose_name='Привилегия'),
        ),
    ]
