# Generated by Django 3.2.18 on 2023-05-16 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230515_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.TextField(choices=[('пользователь', 'пользователь'), ('заблокирован', 'заблокирован'), ('дизайнер', 'дизайнер'), ('главный дизайнер', 'главный дизайнер'), ('куратор', 'куратор'), ('арбитр', 'арбитр'), ('главный арбитр', 'главный арбитр'), ('бот', 'бот'), ('администратор', 'администратор'), ('разработчик', 'разработчик'), ('гл. администратор', 'гл. администратор'), ('владелец', 'владелец')], default='пользователь', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_market_privilege',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 10, 18, 3, 570141, tzinfo=utc), verbose_name='Дата покупки доступа к маркету'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_privilege',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 10, 18, 3, 570141, tzinfo=utc), verbose_name='Дата покупки привилегии'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_buy_profile_sub',
            field=models.DateField(default=datetime.datetime(2023, 5, 16, 10, 18, 3, 570141, tzinfo=utc), verbose_name='Дата покупки фона профиля'),
        ),
    ]
