# Generated by Django 3.2.18 on 2023-04-12 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
