# Generated by Django 3.2.18 on 2023-04-12 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 12, 20, 59, 57, 113257, tzinfo=utc), null=True),
        ),
    ]
