# Generated by Django 3.2.18 on 2023-12-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Рекламный пост', 'verbose_name_plural': 'Рекламные посты'},
        ),
        migrations.RemoveField(
            model_name='ads',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='title',
        ),
        migrations.AddField(
            model_name='ads',
            name='link',
            field=models.SlugField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='weeks',
            field=models.IntegerField(verbose_name='Кол-во оплаченных недель'),
        ),
    ]
