# Generated by Django 3.2.18 on 2023-11-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_viewers_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=55, verbose_name='Категория')),
                ('priority', models.CharField(max_length=55, verbose_name='Приоритет')),
                ('title', models.CharField(max_length=55, verbose_name='Заголовок')),
                ('request', models.CharField(max_length=3, verbose_name='Обращение к админу')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание вопроса')),
            ],
        ),
    ]
