# Generated by Django 3.2.18 on 2023-05-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewers',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='forum.forum', verbose_name='Пост'),
        ),
    ]
