# Generated by Django 3.2.18 on 2023-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20231203_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='title',
            field=models.CharField(default=123, max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
