# Generated by Django 3.2.18 on 2023-04-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20230413_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
