# Generated by Django 3.2.18 on 2023-11-22 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_helpforum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpforum',
            options={'ordering': ('-priority',), 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AddField(
            model_name='helpforum',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpforum',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helpforum',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Описание вопроса'),
        ),
    ]
