# Generated by Django 3.2.16 on 2023-01-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='image_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='text_comment',
        ),
    ]
