# Generated by Django 3.2.18 on 2023-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_ads_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='link',
            field=models.CharField(max_length=10, verbose_name='Ссылка'),
        ),
    ]
