# Generated by Django 3.2.16 on 2023-01-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20230123_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image_comment',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text_comment',
            new_name='text',
        ),
    ]
