# Generated by Django 3.2.18 on 2023-12-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_ads_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='link',
            new_name='post_id',
        ),
    ]
