# Generated by Django 3.2.18 on 2023-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20231122_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpforum',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='helpforum',
            name='category',
            field=models.TextField(choices=[('Разблокировка аккаунта', 'Разблокировка аккаунта'), ('Проблема с пополнением средств', 'Проблема с пополнением средств'), ('Проблема с выводом средств', 'Проблема с выводом средств'), ("Разблокировка с причиной 'Вбив/отмыв'", "Разблокировка с причиной 'Вбив/отмыв'"), ('Возврат средств за привилегию', 'Возврат средств за привилегию'), ('Смена почты на аккаунте', 'Смена почты на аккаунте'), ("Разблокировка с причиной 'Взломан'", "Разблокировка с причиной 'Взломан'"), ('Другое', 'Другое')], default='Разблокировка аккаунта', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='helpforum',
            name='description',
            field=models.TextField(verbose_name='Описание вопроса'),
        ),
        migrations.AlterField(
            model_name='helpforum',
            name='priority',
            field=models.TextField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], default='Низкий', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='helpforum',
            name='request',
            field=models.TextField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default='Нет', verbose_name='Обращение к админу'),
        ),
        migrations.AlterField(
            model_name='helpforum',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
