# Generated by Django 3.2.18 on 2023-05-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрытая тема'),
        ),
    ]
