# Generated by Django 3.2.18 on 2023-12-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_link_ads_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='ad',
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
