# Generated by Django 3.2.16 on 2023-01-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20230123_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='Текст'),
        ),
    ]
