# Generated by Django 3.2.18 on 2023-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forum_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='edit',
            field=models.BooleanField(default=False, verbose_name='Пост был отредактирован'),
        ),
    ]
