# Generated by Django 3.2.18 on 2023-11-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20231123_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpforum',
            name='priority_lvl',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', verbose_name='Уровень приоритета'),
        ),
    ]
