# Generated by Django 3.2.18 on 2023-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_forum_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
