# Generated by Django 3.2.16 on 2023-01-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20230123_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
