# Generated by Django 3.2.16 on 2023-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_forum_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='views',
        ),
        migrations.AddField(
            model_name='forum',
            name='views',
            field=models.ManyToManyField(default=0, related_name='views', to='forum.Ip', verbose_name='Просмотры'),
        ),
    ]
