# Generated by Django 3.2.16 on 2023-01-31 14:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20230124_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный адрес')),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
            },
        ),
        migrations.AddField(
            model_name='follow',
            name='count',
            field=models.IntegerField(default=0, verbose_name=users.models.CustomUser),
        ),
    ]
