# Generated by Django 3.2.18 on 2023-11-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20231124_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpforum',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок'),
        ),
    ]
