# Generated by Django 3.2.18 on 2023-11-25 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0010_alter_helpforum_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='forum.group', verbose_name='Группа')),
                ('helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
        ),
    ]
