# Generated by Django 3.2.18 on 2023-11-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0011_helpers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpforum',
            options={'ordering': ('-open', '-priority_lvl', 'request'), 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AlterField(
            model_name='forum',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('weeks', models.IntegerField(verbose_name='Оплаченных недель')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рекламный пост',
                'verbose_name_plural': 'Рекламный посты',
                'ordering': ('-pub_date',),
            },
        ),
    ]
