# Generated by Django 3.2.18 on 2023-11-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20231129_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='text',
            new_name='description',
        ),
    ]
