# Generated by Django 3.2.18 on 2023-11-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_rename_text_ads_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рекламный пост', 'verbose_name_plural': 'Рекламные посты'},
        ),
    ]
