# Generated by Django 3.2.18 on 2023-11-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_alter_ads_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpforum',
            options={'ordering': ('-open', '-priority_lvl', 'request', '-created'), 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
    ]
