# Generated by Django 3.2.18 on 2023-12-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_alter_helpforum_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecomment',
            name='image',
        ),
    ]
