# Generated by Django 3.2.18 on 2023-12-01 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0018_remove_profilecomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_with_comments', to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
    ]
