# Generated by Django 3.2.18 on 2023-12-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20231202_0031'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profilecomment',
            name='unique_name_in_comment',
        ),
    ]
